#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
PKGDIR="$(dirname "$DIR")";
echo "Building project in path $PKGDIR"
CMD=/snap/bin/npm
cd $PKGDIR
$CMD install $PKGDIR
cd - &> /dev/null

