#!/bin/bash
#cwd=/home/sae/sae-app/bin
cwd=/home/sae/sae-app/nh
#cmd=/usr/bin/node
cmd=/snap/bin/node
args=../bin/www.js
daemonize \
	-E PORT=$(cat $cwd/port) \
        -c $cwd \
        -p $cwd/pid \
        -e $cwd/err \
        -o $cwd/log \
        "$cmd" "$args"
