#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
APP="$(dirname "$DIR")";
CMD=/snap/bin/node
ARGS=$APP/bin/www.js
daemonize \
	-E PORT=$(cat $DIR/port) \
        -c $DIR \
        -p $DIR/pid \
        -e $DIR/err \
        -o $DIR/log \
        "$CMD" "$ARGS"
