#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PID=$(cat $DIR/pid)
TIME=$(date)

>&2 echo "$TIME: Killing $PID" 
kill $PID
TIME=$(date)
>&2 echo "$TIME: Killed: $PID" 
echo "" > $DIR/pid

