[package]
name = "nom-rust"
version = "0.1.0"
authors = ["Mike Ricos <mike.ricos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.116"
